CREATE TABLE executions (
    id              UUID PRIMARY KEY,
    build_number    VARCHAR(50),
    triggered_by    VARCHAR(100),
    branch          VARCHAR(100),
    commit_hash     VARCHAR(100),
    platform        VARCHAR(20)        NOT NULL,
    environment     VARCHAR(50),
    firmware_version VARCHAR(50),
    app_version     VARCHAR(50),
    execution_type  VARCHAR(30),
    cucumber_tags   TEXT,
    feature_paths   TEXT,
    maven_profile   VARCHAR(50),
    parallel        BOOLEAN DEFAULT FALSE,
    retry_count     INT DEFAULT 0,
    jvm_params      TEXT,
    status          VARCHAR(20)        NOT NULL DEFAULT 'PENDING',
    start_time      TIMESTAMP WITH TIME ZONE,
    end_time        TIMESTAMP WITH TIME ZONE,
    duration_ms     BIGINT,
    pass_count      INT DEFAULT 0,
    fail_count      INT DEFAULT 0,
    skip_count      INT DEFAULT 0,
    total_count     INT DEFAULT 0,
    report_path     TEXT,
    workspace_path  TEXT,
    created_at      TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    updated_at      TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

CREATE TABLE execution_features (
    id              UUID PRIMARY KEY,
    execution_id    UUID NOT NULL REFERENCES executions(id) ON DELETE CASCADE,
    feature_name    VARCHAR(255) NOT NULL,
    uri             TEXT,
    status          VARCHAR(20),
    duration_ms     BIGINT,
    pass_count      INT DEFAULT 0,
    fail_count      INT DEFAULT 0,
    skip_count      INT DEFAULT 0
);

CREATE TABLE execution_scenarios (
    id              UUID PRIMARY KEY,
    execution_id    UUID NOT NULL REFERENCES executions(id) ON DELETE CASCADE,
    feature_id      UUID REFERENCES execution_features(id) ON DELETE SET NULL,
    scenario_name   VARCHAR(500) NOT NULL,
    tags            TEXT,
    status          VARCHAR(20),
    duration_ms     BIGINT,
    failure_reason  TEXT,
    device_name     VARCHAR(100),
    screenshot_path TEXT
);

CREATE TABLE execution_steps (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    scenario_id     UUID NOT NULL REFERENCES execution_scenarios(id) ON DELETE CASCADE,
    step_name       TEXT NOT NULL,
    status          VARCHAR(20),
    duration_ms     BIGINT,
    log_text        TEXT,
    screenshot_path TEXT,
    timestamp       TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

CREATE TABLE execution_logs (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    execution_id    UUID NOT NULL REFERENCES executions(id) ON DELETE CASCADE,
    level           VARCHAR(10) DEFAULT 'INFO',
    message         TEXT NOT NULL,
    timestamp       TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

CREATE TABLE devices (
    id              UUID PRIMARY KEY,
    name            VARCHAR(100) NOT NULL,
    platform        VARCHAR(20) NOT NULL,
    udid            VARCHAR(255),
    os_version      VARCHAR(50),
    cloud_provider  VARCHAR(30),
    status          VARCHAR(20) DEFAULT 'AVAILABLE',
    reserved_by     VARCHAR(100),
    reserved_until  TIMESTAMP WITH TIME ZONE,
    last_heartbeat  TIMESTAMP WITH TIME ZONE,
    created_at      TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

CREATE TABLE thermostats (
    id              UUID PRIMARY KEY,
    name            VARCHAR(100),
    serial_port     VARCHAR(100),
    firmware_version VARCHAR(50),
    status          VARCHAR(20) DEFAULT 'ONLINE',
    reserved_by     VARCHAR(100),
    current_execution_id UUID REFERENCES executions(id) ON DELETE SET NULL,
    last_heartbeat  TIMESTAMP WITH TIME ZONE,
    created_at      TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

CREATE TABLE schedules (
    id              UUID PRIMARY KEY,
    name            VARCHAR(100) NOT NULL,
    cron_expression VARCHAR(100) NOT NULL,
    execution_config TEXT NOT NULL,
    enabled         BOOLEAN DEFAULT TRUE,
    last_run_at     TIMESTAMP WITH TIME ZONE,
    next_run_at     TIMESTAMP WITH TIME ZONE,
    created_by      VARCHAR(100),
    created_at      TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

CREATE INDEX idx_executions_status       ON executions(status);
CREATE INDEX idx_executions_created_at   ON executions(created_at DESC);
CREATE INDEX idx_features_execution_id   ON execution_features(execution_id);
CREATE INDEX idx_scenarios_execution_id  ON execution_scenarios(execution_id);
CREATE INDEX idx_scenarios_feature_id    ON execution_scenarios(feature_id);
CREATE INDEX idx_logs_execution_id       ON execution_logs(execution_id, timestamp);
CREATE INDEX idx_steps_scenario_id       ON execution_steps(scenario_id);
CREATE INDEX idx_devices_status          ON devices(status);
CREATE INDEX idx_thermostats_status      ON thermostats(status);
